name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"

    - name: Install just 1.25.2
      uses: RobinThrift/action-setup-just@v1

    - name: "Lint"
      run: |
        just lint-report

    - name: Publish Lint Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: "Lint Results"
        files: |
          lint.junit.xml

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"

    - name: Install just 1.25.2
      uses: RobinThrift/action-setup-just@v1

    - name: "Test"
      env:
        GO_TEST_REPORTER: "github-actions"
      run: |
        just test-report

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: "Test Results"
        files: |
          tests.junit.xml
